version: "3"
services:
    nginx:
        image: nginx:alpine
        container_name: ${PROJECT_NAME}-nginx
        restart: unless-stopped
        environment:
            - VIRTUAL_HOST=api.${PROJECT_NAME}.lol
            - VIRTUAL_PORT=80
        ports:
            - 8578:80
            - 8580:443
        volumes:
            - ./public:/var/www/html/public
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        network_mode: "bridge"
        depends_on:
            - elasticsearch
            - koa
        links:
            - elasticsearch
            - koa

    koa:
        container_name: ${PROJECT_NAME}-koa
        build:
            context: ./
            dockerfile: ./docker/Dockerfile
        command: npm run webpack
        volumes:
            - .:/usr/app/
            - ./node_modules/:/usr/app/node_modules
        ports:
            - 3000:3000
            - 9229:9229
        environment:
            - PORT=3000
            - ELASTIC_URL=http://elasticsearch:9200
        links:
            - database
            - elasticsearch
        network_mode: "bridge"
        depends_on:
            - phpmyadmin
            - kibana

    # Only used to install vendors
    vendors:
        build:
            context: ./
            dockerfile: ./docker/install/Dockerfile
        container_name: ${PROJECT_NAME}-vendors
        volumes:
            - .:/usr/app/
            - ./node_modules/:/usr/app/node_modules

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
        container_name: ${PROJECT_NAME}-elastic
        volumes:
            - ./var/lib/elasticsearch/data:/usr/share/elasticsearch/data:rw
        environment:
            - VIRTUAL_HOST=elastic.${PROJECT_NAME}.lol
            - VIRTUAL_PORT=9200
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - discovery.type=single-node
        ports:
            - 9300:9300
            - 9200:9200
        network_mode: "bridge"

    kibana:
        image: docker.elastic.co/kibana/kibana:7.3.2
        container_name: ${PROJECT_NAME}-kibana
        environment:
            - VIRTUAL_HOST=kibana.${PROJECT_NAME}.lol
            - SERVER_NAME=kibana.${PROJECT_NAME}.lol
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        ports:
            - 9201:5601
        depends_on:
            - elasticsearch
        links:
            - elasticsearch
        network_mode: "bridge"

    database:
        container_name: ${PROJECT_NAME}-db
        image: mariadb
        volumes:
            - ./var/lib/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_DATABASE=${TYPEORM_DATABASE}
            - MYSQL_USER=${TYPEORM_USERNAME}
            - MYSQL_PASSWORD=${TYPEORM_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${TYPEORM_PASSWORD}
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        network_mode: "bridge"

    phpmyadmin:
        container_name: ${PROJECT_NAME}-phpmyadmin
        image: phpmyadmin/phpmyadmin
        environment:
            - VIRTUAL_HOST=phpmyadmin.${PROJECT_NAME}.lol
            - VIRTUAL_PORT=9000
            - MYSQL_USERNAME=${TYPEORM_USERNAME}
            - MYSQL_PASSWORD=${TYPEORM_PASSWORD}
            - PMA_USERNAME=${TYPEORM_USERNAME}
            - PMA_PASSWORD=${TYPEORM_PASSWORD}
            - PMA_HOSTS=${TYPEORM_HOST}
        ports:
            - 9000:80
        links:
            - database
        network_mode: "bridge"

volumes:
    data-nginx:
    data-mkcert:
    data-elastic:
