version: "3"
services:
  koa:
    build: .
    command: npm run start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - core
    links:
      - database
    network_mode: bridge

  webpack:
    command: npm run webpack
    build: .
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules

  database:
    image: mariadb
    volumes:
      - ./var/lib/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_DATABASE=${TYPEORM_DATABASE}
      - MYSQL_USER=${TYPEORM_USERNAME}
      - MYSQL_PASSWORD=${TYPEORM_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${TYPEORM_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    network_mode: bridge

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      # - VIRTUAL_HOST=phpmyadmin.dankbank.local
      - MYSQL_USERNAME=${TYPEORM_USERNAME}
      - MYSQL_PASSWORD=${TYPEORM_PASSWORD}
      - PMA_USERNAME=${TYPEORM_USERNAME}
      - PMA_PASSWORD=${TYPEORM_PASSWORD}
      - PMA_HOSTS=${TYPEORM_HOST}
    ports:
      - 8081:80
    links:
      - database
    network_mode: bridge

  # Emulates a group of services with an almost-empty image
  # Makes koa server wait for others before running
  core:
    image: tianon/true
    restart: "no"
    depends_on:
      - webpack
      - database
      - phpmyadmin
