version: "3"
services:
  koa:
    container_name: ${PROJECT_NAME}-koa
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    command: npm run start
    volumes:
      - .:/usr/app/
      - ./node_modules/:/usr/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      - VIRTUAL_HOST=api.dankbank.lol
      - VIRTUAL_PORT=3000
    depends_on:
      - core
    links:
      - database
    networks:
      - api
      - server

  webpack:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    container_name: ${PROJECT_NAME}-webpack
    command: npm run webpack
    volumes:
      - .:/usr/app/
      - ./node_modules/:/usr/app/node_modules
    networks:
      - server

  # Only used to install vendors
  vendors:
    build:
      context: ./
      dockerfile: ./docker/install/Dockerfile
    container_name: ${PROJECT_NAME}-vendors
    volumes:
      - .:/usr/app/
      - ./node_modules/:/usr/app/node_modules

  nginx-proxy:
    container_name: ${PROJECT_NAME}-nginx-proxy
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - data-nginx:/etc/nginx/conf.d
      - data-nginx:/etc/nginx/vhost.d
      - data-nginx:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - server

  nginx-proxy-companion:
    container_name: ${PROJECT_NAME}-nginx-proxy-companion
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - data-nginx:/etc/nginx/conf.d
      - data-nginx:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock

  database:
    container_name: ${PROJECT_NAME}-db
    image: mariadb
    volumes:
      - ./var/lib/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_DATABASE=${TYPEORM_DATABASE}
      - MYSQL_USER=${TYPEORM_USERNAME}
      - MYSQL_PASSWORD=${TYPEORM_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${TYPEORM_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      - api

  phpmyadmin:
    container_name: ${PROJECT_NAME}-phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - VIRTUAL_HOST=phpmyadmin.dankbank.lol
      - VIRTUAL_PORT=9000
      - MYSQL_USERNAME=${TYPEORM_USERNAME}
      - MYSQL_PASSWORD=${TYPEORM_PASSWORD}
      - PMA_USERNAME=${TYPEORM_USERNAME}
      - PMA_PASSWORD=${TYPEORM_PASSWORD}
      - PMA_HOSTS=${TYPEORM_HOST}
    ports:
      - 9000:80
    links:
      - database
    networks:
      - api

  # Emulates a group of services with an almost-empty image
  # Makes koa server wait for others before running
  core:
    container_name: ${PROJECT_NAME}-core
    image: tianon/true
    restart: "no"
    depends_on:
      - webpack
      - database
      - phpmyadmin
      - nginx-proxy
      - nginx-proxy-companion

volumes:
  data-nginx:
networks:
  api:
  server: